### ISSUE TITLE
Time taking to create server

### ISSUE THREAD

**Issue by brnwlshubh** [uintdev/qrserv#13] opened 2023-12-13 04:02 UTC
Why it is taking too much time?

**Comment by uintdev** [comment] 2023-12-13 13:01
Information on that can be found under [PHILOSOPHY.md](../blob/dfe951ae2ff04e9ddfe44e8ec08db4495dda9265/PHILOSOPHY.md).

In short, due to the app making use of Flutter, there were limited existing resources in terms of file selection and so it all went down to copying the entire file selection into the app's cache. The copying process takes time and especially for huge files. This also introduces other issues, such as temporary increased storage usage.

Ideally, we need a way to select files from storage but only get a full path to those files. I might be eyeing something that might be able to achieve this, but I'll have to test to make sure features (such as multi-file selection) won't be lost and it works as intended.

**Comment by uintdev** [comment] 2023-12-13 19:15
Small update: I had put together a basic test, and it's beginning to look promising. Will need to begin implementing into the app itself to be more certain if it would work. As there's less control over the file manager that would be presented (including the theme and i18n) and it does not offer multi-selection, if all goes well, this will just be an optional way to import files (for those huge ones). The usual downloads/documents app is convenient most of the time and more user friendly, in any case.

Slight concern, though. When it comes to the Play Store, Google is a bit strict when it comes to the usage of MANAGE_EXTERNAL_STORAGE. It would have perfectly legitimate use in this case, so I hope that they also agree on that.

**Comment by uintdev** [comment] 2023-12-15 17:50
Version 2.2.0 has been released with a ‘direct access mode’ that should help avoid such issue with such files.

**Comment by uintdev** [comment] 2023-12-20 09:07
Closing as resolved.

**Closed by uintdev** 2023-12-20 09:07 UTC
